language: ruby

rvm:
  - 2.3.0

services:
   - postgresql

bundler_args: '--without development --deployment'

cache: bundler

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed_fu RAILS_ENV=test

script:
  - bundle exec rspec
