const MAP_KEY = 'AIzaSyDGaEAjurBciJPMrX7Hz5Cgdr2TsYYZqfs';
export const GOOGLE_MAP_API_URL = `https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry,drawing,places&key=${MAP_KEY}`;

export const CENTER_POINT = {
  lat: 36.577124,
  lng: 137.861446
};

export const START_POINT = {
  lat: 36.560606,
  lng: 137.872176
};

export const FINISH_POINT = {
  lat: 36.598034,
  lng: 137.824866
};

export const ADD_COMPARE_RESULT = 'ADD_COMPARE_RESULT';
export const DELETE_RESULT = 'DELETE_RESULT';
export const LOAD_RESULTS = 'LOAD_RESULTS';
export const LOAD_CONTROLS_REQUEST = 'LOAD_CONTROLS_REQUEST';
export const LOAD_CONTROLS_RESULT = 'LOAD_CONTROLS_RESULT';
export const LOAD_RESULTS_REQUEST = 'LOAD_RESULTS_REQUEST';
export const LOAD_RESULTS_RESULT = 'LOAD_RESULTS_RESULT';
export const SUGGEST_ON_CHANGE = 'SUGGEST_ON_CHANGE';
export const SUGGEST_ON_SUGGESTIONS_FETCH_REQUESTED = 'SUGGEST_ON_SUGGESTIONS_FETCH_REQUESTED';
export const SUGGEST_ON_SUGGESTIONS_CLEAR_REQUESTED = 'SUGGEST_ON_SUGGESTIONS_CLEAR_REQUESTED';
export const SUGGEST_ON_SUGGESTION_SELECTED = 'SUGGEST_ON_SUGGESTION_SELECTED';
