default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: omm_result_development
test:
  <<: *default
  database: omm_result_test

production:
  <<: *default
  database: omm_result_production
  username: omm_result
  password: <%= ENV['OMM_RESULT_DATABASE_PASSWORD'] %>
