default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: omm_result_development
test:
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  database: omm_result_production
  username: omm_result
  password: <%= ENV['OMM_RESULT_DATABASE_PASSWORD'] %>
